# Generated by Django 4.2.16 on 2024-09-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departamento", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                (
                    "short_name",
                    models.CharField(max_length=20, verbose_name="Nombre corte"),
                ),
                ("anulate", models.BooleanField(default=False, verbose_name="anulado")),
            ],
        ),
    ]
