# Generated by Django 4.2.16 on 2024-09-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departamento", "0003_alter_departamento_short_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Habilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
            options={"verbose_name": "Skill", "verbose_name_plural": "Skills",},
        ),
        migrations.AlterModelOptions(
            name="departamento",
            options={
                "ordering": ["-name"],
                "verbose_name": "My Departament",
                "verbose_name_plural": "Departaments",
            },
        ),
        migrations.AlterUniqueTogether(
            name="departamento", unique_together={("name", "short_name")},
        ),
    ]
