# Generated by Django 4.2.16 on 2024-09-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departamento", "0004_habilidad_alter_departamento_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prueba",
            name="cantidad",
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
