# Generated by Django 4.2.16 on 2024-09-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Habilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
            options={"verbose_name": "Skill", "verbose_name_plural": "Skills",},
        ),
        migrations.AlterModelOptions(
            name="persona",
            options={
                "ordering": ["-first_name"],
                "verbose_name": "Empleados Taberu",
                "verbose_name_plural": "People Taberu",
            },
        ),
        migrations.AddField(
            model_name="persona",
            name="habilidad",
            field=models.ManyToManyField(to="persona.habilidad"),
        ),
    ]
