# Generated by Django 4.2.16 on 2024-09-24 23:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0002_habilidad_alter_persona_options_persona_habilidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="hoja_vida",
            field=ckeditor.fields.RichTextField(default="text"),
            preserve_default=False,
        ),
    ]
