# Generated by Django 4.2.16 on 2024-09-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0004_rename_departamento_persona_departamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="full_name"
            ),
        ),
    ]
