# Generated by Django 4.2.16 on 2024-10-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0005_persona_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="empleado"),
        ),
    ]
